import numpy as np
def get_tags():
    tags_onehot = {
        'O': np.array([1] + [0] * 41),
        'B-PERS': np.array([0, 1] + [0] * 40),
        'I-PERS': np.array([0] * 2 + [1] + [0] * 39), 
        'B-DATE': np.array([0] * 3 + [1] + [0] * 38), 
        'I-DATE': np.array([0] * 4 + [1] + [0] * 37), 
        'B-ORDINAL': np.array([0] * 5 + [1] + [0] * 36), 
        'I-ORDINAL': np.array([0] * 6 + [1] + [0] * 35), 
        'B-GPE': np.array([0] * 7 + [1] + [0] * 34), 
        'I-GPE': np.array([0] * 8 + [1] + [0] * 33),
        'B-NORP': np.array([0] * 9 + [1] + [0] * 32), 
        'I-NORP': np.array([0] * 10 + [1] + [0] * 31),
        'B-WEBSITE': np.array([0] * 11 + [1] + [0] * 30),
        'I-WEBSITE': np.array([0] * 12 + [1] + [0] * 29),
        'B-CARDINAL': np.array([0] * 13 + [1] + [0] * 28),
        'I-CARDINAL': np.array([0] * 14 + [1] + [0] * 27),
        'B-OCC': np.array([0] * 15 + [1] + [0] * 26),
        'I-OCC': np.array([0] * 16 + [1] + [0] * 25),
        'B-EVENT': np.array([0] * 17 + [1] + [0] * 24),
        'I-EVENT': np.array([0] * 18 + [1] + [0] * 23),
        'B-LOC': np.array([0] * 19 + [1] + [0] * 22), 
        'I-LOC': np.array([0] * 20 + [1] + [0] * 21),
        'B-FAC': np.array([0] * 21 + [1] + [0] * 20),
        'I-FAC': np.array([0] * 22 + [1] + [0] * 19),
        'B-MONEY': np.array([0] * 23 + [1] + [0] * 18), 
        'I-MONEY': np.array([0] * 24 + [1] + [0] * 17),
        'B-TIME': np.array([0] * 25 + [1] + [0] * 16),
        'I-TIME': np.array([0] * 26 + [1] + [0] * 15),
        'B-LANGUAGE': np.array([0] * 27 + [1] + [0] * 14),
        'I-LANGUAGE': np.array([0] * 28 + [1] + [0] * 13),
        'B-UNIT': np.array([0] * 29 + [1] + [0] * 12),
        'B-PRODUCT': np.array([0] * 30 + [1] + [0] * 11),
        'I-PRODUCT': np.array([0] * 31 + [1] + [0] * 10),
        'B-CURR': np.array([0] * 32 + [1] + [0] * 9),
        'I-CURR': np.array([0] * 33 + [1] + [0] * 8),
        'B-PERCENT': np.array([0] * 34 + [1] + [0] * 7),
        'I-PERCENT': np.array([0] * 35 + [1] + [0] * 6),
        'B-LAW': np.array([0] * 36 + [1] + [0] * 5),
        'I-LAW': np.array([0] * 37 + [1] + [0] * 4),
        'B-QUANTITY': np.array([0] * 38 + [1] + [0] * 3),
        'I-QUANTITY': np.array([0] * 39 + [1] + [0] * 2),
        'B-ORG': np.array([0] * 40 + [1] + [0]),
        'I-ORG': np.array([0] * 41 + [1]),
             }

    tags_scores = {
        'O':0,
        'B-PERS':0,
        'I-PERS':0,
        'B-DATE':0,
        'I-DATE':0,
        'B-ORDINAL':0,
        'I-ORDINAL':0,
        'B-GPE':0,
        'I-GPE':0,
        'B-NORP':0,
        'I-NORP':0,
        'B-WEBSITE':0,
        'I-WEBSITE':0,
        'B-CARDINAL':0,
        'I-CARDINAL':0,
        'B-OCC':0,
        'I-OCC':0,
        'B-EVENT':0,
        'I-EVENT':0,
        'B-LOC':0, 
        'I-LOC':0,
        'B-FAC':0,
        'I-FAC':0,
        'B-MONEY':0, 
        'I-MONEY':0,
        'B-TIME':0,
        'I-TIME':0,
        'B-LANGUAGE':0,
        'I-LANGUAGE':0,
        'B-UNIT':0,
        'B-PRODUCT':0,
        'I-PRODUCT':0,
        'B-CURR':0,
        'I-CURR':0,
        'B-PERCENT':0,
        'I-PERCENT':0,
        'B-LAW':0,
        'I-LAW':0,
        'B-QUANTITY':0,
        'I-QUANTITY':0,
        'B-ORG':0,
        'I-ORG':0,
            }
    return tags_onehot, tags_scores